In [3]:
import pandas as pd
import numpy as np

ds = pd.Series([10,20,30,40])
print(ds)

0    10
1    20
2    30
3    40
dtype: int64

In [4]:
import pandas as pd
import numpy as np

ds = pd.Series([10,20,30,40],index=['v','h','A','B'])
print(ds)

v    10
h    20
A    30
B    40
dtype: int64

In [6]:
import pandas as pd
import numpy as np

ds = pd.Series([10,20,30,40],index=['v','h','A','B'],dtype='float')
print(ds)

v    10.0
h    20.0
A    30.0
B    40.0
dtype: float64

In [7]:
import pandas as pd
import numpy as np

ds = pd.Series([10,20,30,40],index=['v','h','A','B'],dtype='float',name='VHA')
print(ds)

v    10.0
h    20.0
A    30.0
B    40.0
Name: VHA, dtype: float64

In [9]:
import pandas as pd
import numpy as np

ds = pd.Series((10,20,30,40),index=['v','h','A','B'],dtype='float',name='VHA')
print(ds)

v    10.0
h    20.0
A    30.0
B    40.0
Name: VHA, dtype: float64

In [12]:
import pandas as pd
import numpy as np

ds = pd.Series({1:"one",2:"two",3:"three",4:"four"},name='VHA')
print(ds)

1      one
2      two
3    three
4     four
Name: VHA, dtype: object

In [16]:
import pandas as pd
import numpy as np

ds = pd.Series(np.array([0,10,20,30]),name='VHA')
print(ds)

0     0
1    10
2    20
3    30
Name: VHA, dtype: int32

In [25]:
import pandas as pd
import numpy as np

ds = pd.DataFrame([['v','h','a'],[10,20,30],[1,2,3]],index=['p','q','r'],columns=['a','b','c'])

print(ds)

    a   b   c
p   v   h   a
q  10  20  30
r   1   2   3

In [28]:
import pandas as pd
import numpy as np

ds = pd.DataFrame({'name':['v','h','a'],'mark':[10,12,14],'cgpa':[9.2,9.5,9.0]},index=['p','q','r'])

print(ds)

  name  mark  cgpa
p    v    10   9.2
q    h    12   9.5
r    a    14   9.0

In [32]:
import pandas as pd
import numpy as np

ds = pd.DataFrame([{'name':'vishal','mark':10},{'name':'kaushal','mark':11},{'name':'VHA','mark':12}],index=['p','q','r'])

print(ds)

      name  mark
p   vishal    10
q  kaushal    11
r      VHA    12

In [54]:
import pandas as pd
import numpy as np

df = pd.read_csv('train.csv')
print(df)
print("---------------------------------------------------------------------------")
print(df.index)
print("---------------------------------------------------------------------------")
print(df.columns)
print("---------------------------------------------------------------------------")
print(df.size)
print("---------------------------------------------------------------------------")
print(df.shape)
print("---------------------------------------------------------------------------")
print(df.values)
print("---------------------------------------------------------------------------")
print(df.dtypes)
print("---------------------------------------------------------------------------")
print(df.ndim)
print("---------------------------------------------------------------------------")
print(df.T)
print("---------------------------------------------------------------------------")
df=df.set_index('Name')
print("---------------------------------------------------------------------------")
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]
---------------------------------------------------------------------------
RangeIndex(start=0, stop=891, step=1)
---------------------------------------------------------------------------
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
---------------------------------------------------------------------------
10692
---------------------------------------------------------------------------
(891, 12)
---------------------------------------------------------------------------
[[1 0 3 ... 7.25 nan 'S']
 [2 1 1 ... 71.2833 'C85' 'C']
 [3 1 3 ... 7.925 nan 'S']
 ...
 [889 0 3 ... 23.45 nan 'S']
 [890 1 1 ... 30.0 'C148' 'C']
 [891 0 3 ... 7.75 nan 'Q']]
---------------------------------------------------------------------------
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object
---------------------------------------------------------------------------
2
---------------------------------------------------------------------------
                                 0    \
PassengerId                        1
Survived                           0
Pclass                             3
Name         Braund, Mr. Owen Harris
Sex                             male
Age                               22
SibSp                              1
Parch                              0
Ticket                     A/5 21171
Fare                            7.25
Cabin                            NaN
Embarked                           S

                                                           1    \
PassengerId                                                  2
Survived                                                     1
Pclass                                                       1
Name         Cumings, Mrs. John Bradley (Florence Briggs Th...
Sex                                                     female
Age                                                         38
SibSp                                                        1
Parch                                                        0
Ticket                                                PC 17599
Fare                                                   71.2833
Cabin                                                      C85
Embarked                                                     C

                                2    \
PassengerId                       3
Survived                          1
Pclass                            3
Name         Heikkinen, Miss. Laina
Sex                          female
Age                              26
SibSp                             0
Parch                             0
Ticket             STON/O2. 3101282
Fare                          7.925
Cabin                           NaN
Embarked                          S

                                                      3    \
PassengerId                                             4
Survived                                                1
Pclass                                                  1
Name         Futrelle, Mrs. Jacques Heath (Lily May Peel)
Sex                                                female
Age                                                    35
SibSp                                                   1
Parch                                                   0
Ticket                                             113803
Fare                                                 53.1
Cabin                                                C123
Embarked                                                S

                                  4                 5    \
PassengerId                         5                 6
Survived                            0                 0
Pclass                              3                 3
Name         Allen, Mr. William Henry  Moran, Mr. James
Sex                              male              male
Age                                35               NaN
SibSp                               0                 0
Parch                               0                 0
Ticket                         373450            330877
Fare                             8.05            8.4583
Cabin                             NaN               NaN
Embarked                            S                 Q

                                 6                               7    \
PassengerId                        7                               8
Survived                           0                               0
Pclass                             1                               3
Name         McCarthy, Mr. Timothy J  Palsson, Master. Gosta Leonard
Sex                             male                            male
Age                               54                               2
SibSp                              0                               3
Parch                              0                               1
Ticket                         17463                          349909
Fare                         51.8625                          21.075
Cabin                            E46                             NaN
Embarked                           S                               S

                                                           8    \
PassengerId                                                  9
Survived                                                     1
Pclass                                                       3
Name         Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
Sex                                                     female
Age                                                         27
SibSp                                                        0
Parch                                                        2
Ticket                                                  347742
Fare                                                   11.1333
Cabin                                                      NaN
Embarked                                                     S

                                             9    ...                 881  \
PassengerId                                   10  ...                 882
Survived                                       1  ...                   0
Pclass                                         2  ...                   3
Name         Nasser, Mrs. Nicholas (Adele Achem)  ...  Markun, Mr. Johann
Sex                                       female  ...                male
Age                                           14  ...                  33
SibSp                                          1  ...                   0
Parch                                          0  ...                   0
Ticket                                    237736  ...              349257
Fare                                     30.0708  ...              7.8958
Cabin                                        NaN  ...                 NaN
Embarked                                       C  ...                   S

                                      882                            883  \
PassengerId                           883                            884
Survived                                0                              0
Pclass                                  3                              2
Name         Dahlberg, Miss. Gerda Ulrika  Banfield, Mr. Frederick James
Sex                                female                           male
Age                                    22                             28
SibSp                                   0                              0
Parch                                   0                              0
Ticket                               7552               C.A./SOTON 34068
Fare                              10.5167                           10.5
Cabin                                 NaN                            NaN
Embarked                                S                              S

                                884                                   885  \
PassengerId                     885                                   886
Survived                          0                                     0
Pclass                            3                                     3
Name         Sutehall, Mr. Henry Jr  Rice, Mrs. William (Margaret Norton)
Sex                            male                                female
Age                              25                                    39
SibSp                             0                                     0
Parch                             0                                     5
Ticket              SOTON/OQ 392076                                382652
Fare                           7.05                                29.125
Cabin                           NaN                                   NaN
Embarked                          S                                     Q

                               886                           887  \
PassengerId                    887                           888
Survived                         0                             1
Pclass                           2                             1
Name         Montvila, Rev. Juozas  Graham, Miss. Margaret Edith
Sex                           male                        female
Age                             27                            19
SibSp                            0                             0
Parch                            0                             0
Ticket                      211536                        112053
Fare                            13                            30
Cabin                          NaN                           B42
Embarked                         S                             S

                                                  888                    889  \
PassengerId                                       889                    890
Survived                                            0                      1
Pclass                                              3                      1
Name         Johnston, Miss. Catherine Helen "Carrie"  Behr, Mr. Karl Howell
Sex                                            female                   male
Age                                               NaN                     26
SibSp                                               1                      0
Parch                                               2                      0
Ticket                                     W./C. 6607                 111369
Fare                                            23.45                     30
Cabin                                             NaN                   C148
Embarked                                            S                      C

                             890
PassengerId                  891
Survived                       0
Pclass                         3
Name         Dooley, Mr. Patrick
Sex                         male
Age                           32
SibSp                          0
Parch                          0
Ticket                    370376
Fare                        7.75
Cabin                        NaN
Embarked                       Q

[12 rows x 891 columns]
---------------------------------------------------------------------------
---------------------------------------------------------------------------
                                                    PassengerId  Survived  \
Name
Braund, Mr. Owen Harris                                       1         0
Cumings, Mrs. John Bradley (Florence Briggs Tha...            2         1
Heikkinen, Miss. Laina                                        3         1
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  4         1
Allen, Mr. William Henry                                      5         0
...                                                         ...       ...
Montvila, Rev. Juozas                                       887         0
Graham, Miss. Margaret Edith                                888         1
Johnston, Miss. Catherine Helen "Carrie"                    889         0
Behr, Mr. Karl Howell                                       890         1
Dooley, Mr. Patrick                                         891         0

                                                    Pclass     Sex   Age  \
Name
Braund, Mr. Owen Harris                                  3    male  22.0
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  38.0
Heikkinen, Miss. Laina                                   3  female  26.0
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  35.0
Allen, Mr. William Henry                                 3    male  35.0
...                                                    ...     ...   ...
Montvila, Rev. Juozas                                    2    male  27.0
Graham, Miss. Margaret Edith                             1  female  19.0
Johnston, Miss. Catherine Helen "Carrie"                 3  female   NaN
Behr, Mr. Karl Howell                                    1    male  26.0
Dooley, Mr. Patrick                                      3    male  32.0

                                                    SibSp  Parch  \
Name
Braund, Mr. Owen Harris                                 1      0
Cumings, Mrs. John Bradley (Florence Briggs Tha...      1      0
Heikkinen, Miss. Laina                                  0      0
Futrelle, Mrs. Jacques Heath (Lily May Peel)            1      0
Allen, Mr. William Henry                                0      0
...                                                   ...    ...
Montvila, Rev. Juozas                                   0      0
Graham, Miss. Margaret Edith                            0      0
Johnston, Miss. Catherine Helen "Carrie"                1      2
Behr, Mr. Karl Howell                                   0      0
Dooley, Mr. Patrick                                     0      0

                                                              Ticket     Fare  \
Name
Braund, Mr. Owen Harris                                    A/5 21171   7.2500
Cumings, Mrs. John Bradley (Florence Briggs Tha...          PC 17599  71.2833
Heikkinen, Miss. Laina                              STON/O2. 3101282   7.9250
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  113803  53.1000
Allen, Mr. William Henry                                      373450   8.0500
...                                                              ...      ...
Montvila, Rev. Juozas                                         211536  13.0000
Graham, Miss. Margaret Edith                                  112053  30.0000
Johnston, Miss. Catherine Helen "Carrie"                  W./C. 6607  23.4500
Behr, Mr. Karl Howell                                         111369  30.0000
Dooley, Mr. Patrick                                           370376   7.7500

                                                   Cabin Embarked
Name
Braund, Mr. Owen Harris                              NaN        S
Cumings, Mrs. John Bradley (Florence Briggs Tha...   C85        C
Heikkinen, Miss. Laina                               NaN        S
Futrelle, Mrs. Jacques Heath (Lily May Peel)        C123        S
Allen, Mr. William Henry                             NaN        S
...                                                  ...      ...
Montvila, Rev. Juozas                                NaN        S
Graham, Miss. Margaret Edith                         B42        S
Johnston, Miss. Catherine Helen "Carrie"             NaN        S
Behr, Mr. Karl Howell                               C148        C
Dooley, Mr. Patrick                                  NaN        Q

[891 rows x 11 columns]

In [55]:
df=df.reset_index()
print("---------------------------------------------------------------------------")
print(df)

---------------------------------------------------------------------------
                                                  Name  PassengerId  Survived  \
0                              Braund, Mr. Owen Harris            1         0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...            2         1
2                               Heikkinen, Miss. Laina            3         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)            4         1
4                             Allen, Mr. William Henry            5         0
..                                                 ...          ...       ...
886                              Montvila, Rev. Juozas          887         0
887                       Graham, Miss. Margaret Edith          888         1
888           Johnston, Miss. Catherine Helen "Carrie"          889         0
889                              Behr, Mr. Karl Howell          890         1
890                                Dooley, Mr. Patrick          891         0

     Pclass     Sex   Age  SibSp  Parch            Ticket     Fare Cabin  \
0         3    male  22.0      1      0         A/5 21171   7.2500   NaN
1         1  female  38.0      1      0          PC 17599  71.2833   C85
2         3  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN
3         1  female  35.0      1      0            113803  53.1000  C123
4         3    male  35.0      0      0            373450   8.0500   NaN
..      ...     ...   ...    ...    ...               ...      ...   ...
886       2    male  27.0      0      0            211536  13.0000   NaN
887       1  female  19.0      0      0            112053  30.0000   B42
888       3  female   NaN      1      2        W./C. 6607  23.4500   NaN
889       1    male  26.0      0      0            111369  30.0000  C148
890       3    male  32.0      0      0            370376   7.7500   NaN

    Embarked
0          S
1          C
2          S
3          S
4          S
..       ...
886        S
887        S
888        S
889        C
890        Q

[891 rows x 12 columns]

In [62]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'name':['v','h','a'],
                   'mark':[10,12,14],
                   'cgpa':[9.2,9.5,9.0]},
                   index=['p','q','r'])


print(df)

  name  mark  cgpa
p    v    10   9.2
q    h    12   9.5
r    a    14   9.0

In [67]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'name':['v','h','a'],
                   'mark':[10,12,14],
                   'cgpa':[9.2,9.5,9.0]},
                   index=['p','q','r'],
                  columns=['name','mark','cqpa'])


print(df)

  name  mark cqpa
p    v    10  NaN
q    h    12  NaN
r    a    14  NaN

In [66]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame({'name':['v','h','a'],
                   'mark':[10,12,14],
                   'cgpa':[9.2,9.5,9.0]},
                   index=['p','q','r'],
                  columns=['name','mark','cgpa'])


df1.set_index('name')

      mark  cgpa
name
v       10   9.2
h       12   9.5
a       14   9.0

In [68]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame({'name':['v','h','a'],
                   'mark':[10,12,14],
                   'cgpa':[9.2,9.5,9.0]},
                   index=['p','q','r'],
                  columns=['name','mark','cgpa'])


df1.set_index('name',drop=True)

      mark  cgpa
name
v       10   9.2
h       12   9.5
a       14   9.0

In [75]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame({'name':['v','h','a'],
                   'mark':[10,12,14],
                   'cgpa':[9.2,9.5,9.0]},
                   index=['p','q','r'],
                  columns=['name','mark','cgpa'])


df1=df1.set_index('name',drop=False)
print(df1)

     name  mark  cgpa
name
v       v    10   9.2
h       h    12   9.5
a       a    14   9.0

In [82]:
df=pd.read_csv('train.csv')
print(df)
df['Name']
print("--------------------------------------------------------------------------")
type(df['Name'])

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]
--------------------------------------------------------------------------

pandas.core.series.Series

In [83]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [85]:
df[['Name','Pclass']]

                                                  Name  Pclass
0                              Braund, Mr. Owen Harris       3
1    Cumings, Mrs. John Bradley (Florence Briggs Th...       1
2                               Heikkinen, Miss. Laina       3
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)       1
4                             Allen, Mr. William Henry       3
..                                                 ...     ...
886                              Montvila, Rev. Juozas       2
887                       Graham, Miss. Margaret Edith       1
888           Johnston, Miss. Catherine Helen "Carrie"       3
889                              Behr, Mr. Karl Howell       1
890                                Dooley, Mr. Patrick       3

[891 rows x 2 columns]

In [87]:
df=pd.read_csv('train.csv')
print(df)
df['Name']
print("--------------------------------------------------------------------------")

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]
--------------------------------------------------------------------------

3

In [88]:
df.iloc[2,2]

3

In [89]:
df.iloc[2]

PassengerId                         3
Survived                            1
Pclass                              3
Name           Heikkinen, Miss. Laina
Sex                            female
Age                                26
SibSp                               0
Parch                               0
Ticket               STON/O2. 3101282
Fare                            7.925
Cabin                             NaN
Embarked                            S
Name: 2, dtype: object

In [91]:
df.iloc[2:3,:]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925,NaN,S

In [92]:
df.iloc[1:10,2:5]

   Pclass                                               Name     Sex
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2       3                             Heikkinen, Miss. Laina  female
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4       3                           Allen, Mr. William Henry    male
5       3                                   Moran, Mr. James    male
6       1                            McCarthy, Mr. Timothy J    male
7       3                     Palsson, Master. Gosta Leonard    male
8       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female
9       2                Nasser, Mrs. Nicholas (Adele Achem)  female

In [94]:
df=df.set_index('Name')

In [98]:
df.loc['Cumings, Mrs. John Bradley (Florence Briggs Thayer)']

PassengerId           2
Survived              1
Pclass                1
Sex              female
Age                  38
SibSp                 1
Parch                 0
Ticket         PC 17599
Fare            71.2833
Cabin               C85
Embarked              C
Name: Cumings, Mrs. John Bradley (Florence Briggs Thayer), dtype: object

In [100]:
df.loc['Cumings, Mrs. John Bradley (Florence Briggs Thayer)':'Devaney, Miss. Margaret Delia','PassengerId':'Age']

,PassengerId,Survived,Pclass,Sex,Age
Name,,,,,
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0
"Heikkinen, Miss. Laina",3,1,3,female,26.0
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0
"Allen, Mr. William Henry",5,0,3,male,35.0
"Moran, Mr. James",6,0,3,male,NaN
"McCarthy, Mr. Timothy J",7,0,1,male,54.0
"Palsson, Master. Gosta Leonard",8,0,3,male,2.0
"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",9,1,3,female,27.0
"Nasser, Mrs. Nicholas (Adele Achem)",10,1,2,female,14.0
"Sandstrom, Miss. Marguerite Rut",11,1,3,female,4.0
"Bonnell, Miss. Elizabeth",12,1,1,female,58.0
"Saundercock, Mr. William Henry",13,0,3,male,20.0
"Andersson, Mr. Anders Johan",14,0,3,male,39.0
"Vestrom, Miss. Hulda Amanda Adolfina",15,0,3,female,14.0
"Hewlett, Mrs. (Mary D Kingcome)",16,1,2,female,55.0
"Rice, Master. Eugene",17,0,3,male,2.0
"Williams, Mr. Charles Eugene",18,1,2,male,NaN
"Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)",19,0,3,female,31.0
"Masselmani, Mrs. Fatima",20,1,3,female,NaN
"Fynney, Mr. Joseph J",21,0,2,male,35.0
"Beesley, Mr. Lawrence",22,1,2,male,34.0
"McGowan, Miss. Anna ""Annie""",23,1,3,female,15.0
"Sloper, Mr. William Thompson",24,1,1,male,28.0
"Palsson, Miss. Torborg Danira",25,0,3,female,8.0
"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)",26,1,3,female,38.0
"Emir, Mr. Farred Chehab",27,0,3,male,NaN
"Fortune, Mr. Charles Alexander",28,0,1,male,19.0
"O'Dwyer, Miss. Ellen ""Nellie""",29,1,3,female,NaN
"Todoroff, Mr. Lalio",30,0,3,male,NaN
"Uruchurtu, Don. Manuel E",31,0,1,male,40.0
"Spencer, Mrs. William Augustus (Marie Eugenie)",32,1,1,female,NaN
"Glynn, Miss. Mary Agatha",33,1,3,female,NaN
"Wheadon, Mr. Edward H",34,0,2,male,66.0
"Meyer, Mr. Edgar Joseph",35,0,1,male,28.0
"Holverson, Mr. Alexander Oskar",36,0,1,male,42.0
"Mamee, Mr. Hanna",37,1,3,male,NaN
"Cann, Mr. Ernest Charles",38,0,3,male,21.0
"Vander Planke, Miss. Augusta Maria",39,0,3,female,18.0
"Nicola-Yarred, Miss. Jamila",40,1,3,female,14.0
"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",41,0,3,female,40.0
"Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)",42,0,2,female,27.0
"Kraeff, Mr. Theodor",43,0,3,male,NaN
"Laroche, Miss. Simonne Marie Anne Andree",44,1,2,female,3.0
"Devaney, Miss. Margaret Delia",45,1,3,female,19.0

In [118]:
import pandas as pd
import numpy as np

df = pd.DataFrame([[10,40,70],[20,50,80],[30,60,90]],
                   index=['A','B','C'],
                  columns=['P','Q','R'])


print(df)

    P   Q   R
A  10  40  70
B  20  50  80
C  30  60  90

In [107]:
df.loc["B","Q"]

50

In [108]:
df.loc["B"]

P    20
Q    50
R    80
Name: B, dtype: int64

In [115]:
df.loc[:,'R']

A    70
B    80
C    90
Name: R, dtype: int64

In [119]:
print(df)
df.loc["B","Q"]=100
print(df)

    P   Q   R
A  10  40  70
B  20  50  80
C  30  60  90
    P    Q   R
A  10   40  70
B  20  100  80
C  30   60  90

In [121]:
df['D']=7
print(df)

    P    Q   R  D
A  10   40  70  7
B  20  100  80  7
C  30   60  90  7

In [122]:
print(df)
df["D"]=df['P']*df['Q']
print(df)

    P    Q   R  D
A  10   40  70  7
B  20  100  80  7
C  30   60  90  7
    P    Q   R     D
A  10   40  70   400
B  20  100  80  2000
C  30   60  90  1800

In [124]:
df.loc['A':'C','P':'R']

    P    Q   R
A  10   40  70
B  20  100  80
C  30   60  90