In [12]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.io as pio
pio.renderers.default="notebook"

In [17]:
df=pd.read_csv("social_media_engagement.csv")

In [5]:
df

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative
4,5,Twitter,video,5/23/2023 0:30,3499,247,286,Tuesday,positive
...,...,...,...,...,...,...,...,...,...
95,96,Instagram,carousel,7/12/2023 17:45,36,294,911,Wednesday,positive
96,97,Twitter,video,10/27/2023 23:45,314,108,458,Friday,neutral
97,98,Twitter,text,8/5/2023 8:45,229,179,38,Saturday,positive
98,99,Instagram,poll,12/29/2023 12:15,5000,500,204,Friday,positive
99,100,Instagram,image,6/6/2023 21:00,4483,357,25,Tuesday,neutral

In [7]:
df.dtypes

post_id             int64
platform           object
post_type          object
post_time          object
likes               int64
comments            int64
shares              int64
post_day           object
sentiment_score    object
dtype: object

In [23]:
fig = px.bar(data_frame=df,x='post_type',y='likes',text_auto=True,color="platform",color_discrete_sequence=["black","blue","green"])
fig.show()

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [37]:
fig = px.bar(data_frame=df,
             x='post_type',
             y='likes',
             text_auto=True,
             height=1000,
             width=1000,
             title="platform wise post",
             color="comments",
              hover_data=['post_day','sentiment_score'],
             color_discrete_map={"Facebook":"black","Instagram":"blue","Twitter":"green"})
fig.show()

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [39]:
fig = px.bar(data_frame=df,
             x='post_type',
             y='likes',
             text_auto=True,
             height=1000,
             width=1000,
             title="platform wise post",
             color="comments",
             hover_data=['post_day','sentiment_score'],
             color_discrete_map={"Facebook":"black","Instagram":"blue","Twitter":"green"})
fig.show()

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [40]:
df

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative
4,5,Twitter,video,5/23/2023 0:30,3499,247,286,Tuesday,positive
...,...,...,...,...,...,...,...,...,...
95,96,Instagram,carousel,7/12/2023 17:45,36,294,911,Wednesday,positive
96,97,Twitter,video,10/27/2023 23:45,314,108,458,Friday,neutral
97,98,Twitter,text,8/5/2023 8:45,229,179,38,Saturday,positive
98,99,Instagram,poll,12/29/2023 12:15,5000,500,204,Friday,positive
99,100,Instagram,image,6/6/2023 21:00,4483,357,25,Tuesday,neutral

In [41]:
px.bar(data_frame=df,
             x='post_type',
             y=['likes','comments','shares'],
       color="platform",
       text="comments",
       barmode="stack")

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [42]:
px.bar(data_frame=df,
             x='post_type',
             y=['likes','comments','shares'],
       color="platform",
       text="comments",
       barmode="group")

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [43]:
px.bar(data_frame=df,
             x='post_type',
             y=['likes','comments','shares'],
       color="platform",
       text="comments",
       barmode="group",
       pattern_shape='sentiment_score'
      )

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [44]:
df

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative
4,5,Twitter,video,5/23/2023 0:30,3499,247,286,Tuesday,positive
...,...,...,...,...,...,...,...,...,...
95,96,Instagram,carousel,7/12/2023 17:45,36,294,911,Wednesday,positive
96,97,Twitter,video,10/27/2023 23:45,314,108,458,Friday,neutral
97,98,Twitter,text,8/5/2023 8:45,229,179,38,Saturday,positive
98,99,Instagram,poll,12/29/2023 12:15,5000,500,204,Friday,positive
99,100,Instagram,image,6/6/2023 21:00,4483,357,25,Tuesday,neutral

In [50]:
fig = px.bar(data_frame=df,
             x='post_type',
             y='likes',
             text_auto=True,
             height=1000,
             width=1000,
             title="platform wise post",
             color="comments",
             facet_col='sentiment_score',
             facet_row="post_day",
             
             hover_data=['post_day','sentiment_score'],
             color_discrete_map={"Facebook":"black","Instagram":"blue","Twitter":"green"})
fig.show()

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [52]:
px.scatter(data_frame=df,x='likes',y="comments")

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [53]:
px.scatter(data_frame=df,
           x='likes',
           y="comments",
           color="platform"
          )

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [57]:
px.scatter(data_frame=df,
           x='likes',
           y="comments",
           color="platform",
           symbol="platform"
          )

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [58]:
px.scatter(data_frame=df,
           x='likes',
           y="comments",
           color="platform",
           symbol="platform",
           size="shares"
          )

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [60]:
px.scatter(data_frame=df,
           x='likes',
           y="comments",
           color="platform",
           size="shares"
          )

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [65]:
fig=px.scatter(data_frame=df,
         x='post_type',
         y='likes',
         height=1000,
         width=1000,
         size="shares",
         title="platform wise post",
         color="comments",
         facet_col='sentiment_score',
         facet_row="post_day",

         hover_data=['post_day','sentiment_score'],
         color_discrete_map={"Facebook":"black","Instagram":"blue","Twitter":"green"})
fig.show()

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [69]:
px.scatter_3d(data_frame=df,height=1000,width=700,
             x='likes',
              y="comments",
              z="shares",
              color="platform",
              size="likes",
             )

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [71]:
px.scatter_matrix(data_frame=df,
                  dimensions=["likes","comments","shares"],
                  color="platform",
                  size="likes"
                 
                 )

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [72]:
df

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative
4,5,Twitter,video,5/23/2023 0:30,3499,247,286,Tuesday,positive
...,...,...,...,...,...,...,...,...,...
95,96,Instagram,carousel,7/12/2023 17:45,36,294,911,Wednesday,positive
96,97,Twitter,video,10/27/2023 23:45,314,108,458,Friday,neutral
97,98,Twitter,text,8/5/2023 8:45,229,179,38,Saturday,positive
98,99,Instagram,poll,12/29/2023 12:15,5000,500,204,Friday,positive
99,100,Instagram,image,6/6/2023 21:00,4483,357,25,Tuesday,neutral

In [79]:
px.line(data_frame=df,
        x="post_id",
        y="likes",
        color="post_type",
        hover_data="sentiment_score",
        markers=True
       )

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [80]:
data=df.groupby("platform", as_index=False)[["likes","comments","shares"]].sum()

In [81]:
data

    platform   likes  comments  shares
0   Facebook   86392      7965   15180
1  Instagram  107994      8368   18906
2    Twitter   43795      3933    7479

In [87]:
fig=px.pie(data_frame=data,names="platform",values="likes")
fig.update_traces(textinfo="percent+label",textposition="outside",pull=[0.2,0,0])

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [88]:
df=pd.DataFrame({"dep":["hr","it","hr","it","admit","hr","it"],
                 "salary":[1000,500,700,800,900,1200,1500],
                 "age":[20,25,30,35,22,32,45],
                 "gender":["F","M","F","F","M","F","M"]
                 
                })

In [89]:
df

     dep  salary  age gender
0     hr    1000   20      F
1     it     500   25      M
2     hr     700   30      F
3     it     800   35      F
4  admit     900   22      M
5     hr    1200   32      F
6     it    1500   45      M

In [92]:
px.histogram(data_frame=df,x="age",nbins=20,color="gender")

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [93]:
px.histogram(data_frame=df,x="dep",y="salary",histfunc="max")

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [96]:
px.histogram(data_frame=df,
             x="dep",
             y="salary",
             histfunc="avg",
             color="gender",
            )

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(