In [1]:
import pandas as pd
data={"calories":[420,380,400,370],"duration":[50,40,45,35]}
df=pd.DataFrame(data,index=['day1','day2','day3','day4'])
print(df)
print("--------------------------------------")
print(df.loc['day1','calories'])

      calories  duration
day1       420        50
day2       380        40
day3       400        45
day4       370        35
--------------------------------------
420

## PB55 Create a Pandas DataFrame from the following table and write code to remove all rows from this table containing at least one NaN value

In [2]:
import numpy as np
df=pd.DataFrame({
    "name":['William','Emma','Sofia','Markus','Edward','Thomas','Ethan',np.nan,'Arjun','Anika','Paulo'],
    'region':[np.nan,'North','East',np.nan,'West','West','South',np.nan,"West",'East','South'],
    'sales':[50000,52000,np.nan,np.nan,42000,72000,49000,np.nan,67000,65000,67000],
    'expances':[42000,43000,np.nan,np.nan,38000,39000,42000,np.nan,39000,50000,45000]
})
df

       name region    sales  expances
0   William    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
2     Sofia   East      NaN       NaN
3    Markus    NaN      NaN       NaN
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
7       NaN    NaN      NaN       NaN
8     Arjun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

In [3]:
df.dropna(how="any")

      name region    sales  expances
1     Emma  North  52000.0   43000.0
4   Edward   West  42000.0   38000.0
5   Thomas   West  72000.0   39000.0
6    Ethan  South  49000.0   42000.0
8    Arjun   West  67000.0   39000.0
9    Anika   East  65000.0   50000.0
10   Paulo  South  67000.0   45000.0

## PB56 Create a Pandas DataFrame from the following table and write code to remove all rows from this table only if all of their values are NaN

In [4]:
df.dropna(how="all")

       name region    sales  expances
0   William    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
2     Sofia   East      NaN       NaN
3    Markus    NaN      NaN       NaN
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
8     Arjun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

## PB57 Create a Pandas DataFrame from the following table and write code to drop all columns containing NaN

In [5]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## PB59 Convert this to a Pandas DataFrame and remove duplicate rows from it. Reset index values.

In [6]:
import pandas as pd
data = {
 "A": ["TeamA", "TeamB", "TeamB", "TeamC", "TeamA"],
 "B": [50, 40, 40, 30, 50],
 "C": [True, False, False, False, True]
}
df=pd.DataFrame(data)
df

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
2  TeamB  40  False
3  TeamC  30  False
4  TeamA  50   True

In [7]:
df.drop_duplicates(inplace=True)
df

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
3  TeamC  30  False

In [8]:
df.reset_index(drop=True)

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
2  TeamC  30  False

Q62 Use the file ipl-matches.csv which contains data of all the IPL matches from year 2008 to 2022. Read this csv file and display the basic information like memory and data types for this data frame. Write python code for the following cases:
1. List out all matches gone in superover.
2. How Many Matches won by Chennai Super Kings at Kolkata.
3. In How Many Matches MS Dhoni is Player of Match Vs Mumbai Indians.
4. Display list of all matches in which Gujarat Titans won the Toss and Elected to Bat and won the match.
5. Display list of all matches won by Gujarat Titans.

In [12]:
import pandas as pd
df=pd.read_csv("ipl-matches.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 148.6+ KB

In [13]:
df.isna().sum()

ID                   0
City                51
Date                 0
Season               0
MatchNumber          0
Team1                0
Team2                0
Venue                0
TossWinner           0
TossDecision         0
SuperOver            4
WinningTeam          4
WonBy                0
Margin              18
method             931
Player_of_Match      4
Team1Players         0
Team2Players         0
Umpire1              0
Umpire2              0
dtype: int64

In [14]:
df1=df[df["SuperOver"]=="Y"]
df1

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
114,1254077,Chennai,2021-04-25,2021,20,Delhi Capitals,Sunrisers Hyderabad,"MA Chidambaram Stadium, Chepauk, Chennai",Delhi Capitals,bat,Y,Delhi Capitals,SuperOver,NaN,NaN,PP Shaw,"['PP Shaw', 'S Dhawan', 'RR Pant', 'SPD Smith'...","['DA Warner', 'JM Bairstow', 'KS Williamson', ...",CB Gaffaney,KN Ananthapadmanabhan
158,1216512,Abu Dhabi,2020-10-18,2020/21,35,Kolkata Knight Riders,Sunrisers Hyderabad,Sheikh Zayed Stadium,Sunrisers Hyderabad,field,Y,Kolkata Knight Riders,SuperOver,NaN,NaN,LH Ferguson,"['Shubman Gill', 'RA Tripathi', 'N Rana', 'AD ...","['JM Bairstow', 'KS Williamson', 'PK Garg', 'D...",PG Pathak,S Ravi
159,1216517,NaN,2020-10-18,2020/21,36,Mumbai Indians,Kings XI Punjab,Dubai International Cricket Stadium,Mumbai Indians,bat,Y,Kings XI Punjab,SuperOver,NaN,NaN,KL Rahul,"['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...","['KL Rahul', 'MA Agarwal', 'CH Gayle', 'N Poor...",Nitin Menon,PR Reiffel
184,1216547,NaN,2020-09-28,2020/21,10,Royal Challengers Bangalore,Mumbai Indians,Dubai International Cricket Stadium,Mumbai Indians,field,Y,Royal Challengers Bangalore,SuperOver,NaN,NaN,AB de Villiers,"['D Padikkal', 'AJ Finch', 'V Kohli', 'AB de V...","['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...",Nitin Menon,PR Reiffel
192,1216493,NaN,2020-09-20,2020/21,2,Delhi Capitals,Kings XI Punjab,Dubai International Cricket Stadium,Kings XI Punjab,field,Y,Delhi Capitals,SuperOver,NaN,NaN,MP Stoinis,"['PP Shaw', 'S Dhawan', 'SO Hetmyer', 'SS Iyer...","['KL Rahul', 'MA Agarwal', 'KK Nair', 'N Poora...",AK Chaudhary,Nitin Menon
203,1178426,Mumbai,2019-05-02,2019,51,Mumbai Indians,Sunrisers Hyderabad,Wankhede Stadium,Mumbai Indians,bat,Y,Mumbai Indians,SuperOver,NaN,NaN,JJ Bumrah,"['RG Sharma', 'Q de Kock', 'SA Yadav', 'E Lewi...","['WP Saha', 'MJ Guptill', 'MK Pandey', 'KS Wil...",CK Nandan,S Ravi
244,1175365,Delhi,2019-03-30,2019,10,Kolkata Knight Riders,Delhi Capitals,Arun Jaitley Stadium,Delhi Capitals,field,Y,Delhi Capitals,SuperOver,NaN,NaN,PP Shaw,"['NS Naik', 'CA Lynn', 'RV Uthappa', 'N Rana',...","['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...",AY Dandekar,Nitin Menon
339,1082625,Rajkot,2017-04-29,2017,35,Gujarat Lions,Mumbai Indians,Saurashtra Cricket Association Stadium,Gujarat Lions,bat,Y,Mumbai Indians,SuperOver,NaN,NaN,KH Pandya,"['Ishan Kishan', 'BB McCullum', 'SK Raina', 'A...","['PA Patel', 'JC Buttler', 'N Rana', 'RG Sharm...",AK Chaudhary,CB Gaffaney
474,829741,Ahmedabad,2015-04-21,2015,18,Rajasthan Royals,Kings XI Punjab,"Sardar Patel Stadium, Motera",Kings XI Punjab,field,Y,Kings XI Punjab,SuperOver,NaN,NaN,SE Marsh,"['AM Rahane', 'SR Watson', 'DJ Hooda', 'SPD Sm...","['M Vijay', 'V Sehwag', 'SE Marsh', 'GJ Maxwel...",M Erasmus,S Ravi
533,729315,Abu Dhabi,2014-04-29,2014,19,Kolkata Knight Riders,Rajasthan Royals,Sheikh Zayed Stadium,Rajasthan Royals,bat,Y,Rajasthan Royals,SuperOver,NaN,NaN,JP Faulkner,"['G Gambhir', 'MS Bisla', 'JH Kallis', 'MK Pan...","['AM Rahane', 'KK Nair', 'SV Samson', 'SR Wats...",Aleem Dar,AK Chaudhary
608,598017,Bangalore,2013-04-16,2013,21,Royal Challengers Bangalore,Delhi Daredevils,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Y,Royal Challengers Bangalore,SuperOver,NaN,NaN,V Kohli,"['CH Gayle', 'KL Rahul', 'V Kohli', 'AB de Vil...","['DA Warner', 'V Sehwag', 'MC Juneja', 'DPMD J...",M Erasmus,VA Kulkarni
621,598004,Hyderabad,2013-04-07,2013,7,Sunrisers Hyderabad,Royal Challengers Bangalore,"Rajiv Gandhi International Stadium, Uppal",Royal Challengers Bangalore,bat,Y,Sunrisers Hyderabad,SuperOver,NaN,NaN,GH Vihari,"['PA Reddy', 'PA Patel', 'CL White', 'GH Vihar...","['CH Gayle', 'TM Dilshan', 'V Kohli', 'KK Nair...",AK Chaudhary,S Ravi
819,419121,Chennai,2010-03-21,2009/10,16,Chennai Super Kings,Kings XI Punjab,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,field,Y,Kings XI Punjab,SuperOver,NaN,NaN,J Theron,"['PA Patel', 'ML Hayden', 'SK Raina', 'M Vijay...","['RS Bopara', 'IK Pathan', 'KC Sangakkara', 'D...",K Hariharan,DJ Harper
883,392190,Cape Town,2009-04-23,2009,10,Kolkata Knight Riders,Rajasthan Royals,Newlands,Kolkata Knight Riders,field,Y,Rajasthan Royals,SuperOver,NaN,NaN,YK Pathan,"['CH Gayle', 'BB McCullum', 'LR Shukla', 'BJ H...","['GC Smith', 'PC Valthaty', 'RJ Quiney', 'YK P...",MR Benson,M Erasmus

In [ ]:
df[(df["WinningTeam"]=="Chennai Super Kings") & (df["City"]=="Kolkata")].shape[0]

In [ ]:
df[(df["Player_of_Match"]=="MS Dhoni") & ((df["Team1"]=="Mumbai Indians")|(df["Team2"]=="Mumbai Indians"))]

In [15]:
df[(
    (
        (df["Team1"]=="Gujarat Titans")|
     (df["Team2"]=="Gujarat Titans")
    )&
    (df["TossWinner"]=="Gujarat Titans")&
    (df["TossDecision"]=="bat")&
    (df["WinningTeam"]=="Gujarat Titans")
)]

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
17,1304103,Pune,2022-05-10,2022,57,Gujarat Titans,Lucknow Super Giants,"Maharashtra Cricket Association Stadium, Pune",Gujarat Titans,bat,N,Gujarat Titans,Runs,62.0,NaN,Shubman Gill,"['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...","['Q de Kock', 'KL Rahul', 'DJ Hooda', 'KS Shar...",KN Ananthapadmanabhan,MA Gough
39,1304081,Navi Mumbai,2022-04-23,2022,35,Gujarat Titans,Kolkata Knight Riders,"Dr DY Patil Sports Academy, Mumbai",Gujarat Titans,bat,N,Gujarat Titans,Runs,8.0,NaN,Rashid Khan,"['WP Saha', 'Shubman Gill', 'HH Pandya', 'DA M...","['SW Billings', 'SP Narine', 'SS Iyer', 'N Ran...",KN Ananthapadmanabhan,UV Gandhe

In [16]:
df[(df["WinningTeam"]=="Gujarat Titans")]

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
12,1304108,Mumbai,2022-05-15,2022,62,Chennai Super Kings,Gujarat Titans,"Wankhede Stadium, Mumbai",Chennai Super Kings,bat,N,Gujarat Titans,Wickets,7.0,NaN,WP Saha,"['RD Gaikwad', 'DP Conway', 'MM Ali', 'N Jagad...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",R Pandit,VK Sharma
17,1304103,Pune,2022-05-10,2022,57,Gujarat Titans,Lucknow Super Giants,"Maharashtra Cricket Association Stadium, Pune",Gujarat Titans,bat,N,Gujarat Titans,Runs,62.0,NaN,Shubman Gill,"['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...","['Q de Kock', 'KL Rahul', 'DJ Hooda', 'KS Shar...",KN Ananthapadmanabhan,MA Gough
31,1304089,Mumbai,2022-04-30,2022,43,Royal Challengers Bangalore,Gujarat Titans,"Brabourne Stadium, Mumbai",Royal Challengers Bangalore,bat,N,Gujarat Titans,Wickets,6.0,NaN,R Tewatia,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['WP Saha', 'Shubman Gill', 'B Sai Sudharsan',...",HAS Khalid,VK Sharma
34,1304086,Mumbai,2022-04-27,2022,40,Sunrisers Hyderabad,Gujarat Titans,"Wankhede Stadium, Mumbai",Gujarat Titans,field,N,Gujarat Titans,Wickets,5.0,NaN,Umran Malik,"['Abhishek Sharma', 'KS Williamson', 'RA Tripa...","['WP Saha', 'Shubman Gill', 'HH Pandya', 'DA M...",CB Gaffaney,Navdeep Singh
39,1304081,Navi Mumbai,2022-04-23,2022,35,Gujarat Titans,Kolkata Knight Riders,"Dr DY Patil Sports Academy, Mumbai",Gujarat Titans,bat,N,Gujarat Titans,Runs,8.0,NaN,Rashid Khan,"['WP Saha', 'Shubman Gill', 'HH Pandya', 'DA M...","['SW Billings', 'SP Narine', 'SS Iyer', 'N Ran...",KN Ananthapadmanabhan,UV Gandhe
45,1304075,Pune,2022-04-17,2022,29,Chennai Super Kings,Gujarat Titans,"Maharashtra Cricket Association Stadium, Pune",Gujarat Titans,field,N,Gujarat Titans,Wickets,3.0,NaN,DA Miller,"['RD Gaikwad', 'RV Uthappa', 'MM Ali', 'AT Ray...","['WP Saha', 'Shubman Gill', 'V Shankar', 'A Ma...",KN Ananthapadmanabhan,UV Gandhe
50,1304070,Mumbai,2022-04-14,2022,24,Gujarat Titans,Rajasthan Royals,"Dr DY Patil Sports Academy, Mumbai",Rajasthan Royals,field,N,Gujarat Titans,Runs,37.0,NaN,HH Pandya,"['MS Wade', 'Shubman Gill', 'V Shankar', 'HH P...","['JC Buttler', 'D Padikkal', 'R Ashwin', 'SV S...",CB Gaffaney,R Pandit
58,1304062,Mumbai,2022-04-08,2022,16,Punjab Kings,Gujarat Titans,"Brabourne Stadium, Mumbai",Gujarat Titans,field,N,Gujarat Titans,Wickets,6.0,NaN,Shubman Gill,"['MA Agarwal', 'S Dhawan', 'JM Bairstow', 'LS ...","['MS Wade', 'Shubman Gill', 'B Sai Sudharsan',...",AK Chaudhary,VK Sharma
64,1304056,Pune,2022-04-02,2022,10,Gujarat Titans,Delhi Capitals,"Maharashtra Cricket Association Stadium, Pune",Delhi Capitals,field,N,Gujarat Titans,Runs,14.0,NaN,LH Ferguson,"['MS Wade', 'Shubman Gill', 'V Shankar', 'HH P...","['PP Shaw', 'TL Seifert', 'Mandeep Singh', 'RR...",KN Ananthapadmanabhan,UV Gandhe
70,1304050,Mumbai,2022-03-28,2022,4,Lucknow Super Giants,Gujarat Titans,"Wankhede Stadium, Mumbai",Gujarat Titans,field,N,Gujarat Titans,Wickets,5.0,NaN,Mohammed Shami,"['KL Rahul', 'Q de Kock', 'E Lewis', 'MK Pande...","['Shubman Gill', 'MS Wade', 'V Shankar', 'HH P...",PG Pathak,VK Sharma

## Q67
### 1.How many matches were won by Gujarat Titans in a Super Over ?
### 2.How Many Matches won by Royal Challengers Bangalore Vs Kolkata Knight Riders.
### 3.How many Matches won by Toss Winner of the Match.
### 4.In how many matches was the result decided by the D/L method and the match was won by wickets?
### 5.In how many matches Toss won by Rajasthan Royals & Won the Match.
### 6.In how many matches V Kohli declared player of the match against Chennai Super Kings.
### 7.Which Team is the Toss Winner of the Final match Played in Dubai?
### 8.List out the Finals played by Kolkata Knight Riders in which Toss Won by Kolkata Knight Riders in the Finals and choose to field.

In [ ]:
df[(df["WinningTeam"]=="Gujarat Titans")&(df["SuperOver"]=="Y")]

In [ ]:
df[(((df["Team1"]=="Kolkata Knight Riders")|(df["Team2"]=="Kolkata Knight Riders"))& (df["WinningTeam"]=="Royal Challengers Bangalore"))].shape[0]

In [ ]:
df[df["WinningTeam"]==df["TossWinner"]].shape[0]

In [ ]:
df[((df["method"]=="D/L")&(df["WonBy"]=="Wickets"))].shape[0]

In [ ]:
df[((df["WinningTeam"]=="Rajasthan Royals")&(df["TossWinner"]=="Rajasthan Royals"))].shape[0]

In [ ]:
df[((df["Player_of_Match"]=="V Kohli")&((df["Team1"]=="Chennai Super Kings")|(df["Team2"]=="Chennai Super Kings")))]

In [ ]:
df[(df["MatchNumber"]=="Final")&(df["City"]=="Dubai")]

In [ ]:
df[((df["MatchNumber"]=="Final")&(df["TossWinner"]=="Kolkata Knight Riders")&(df["TossDecision"]=="field"))]

## Q64
Write Python Code for the following cases:
### 1.How Many ritz car are there with kms driven more than 30000km.
### 2.How many Petrol cars are of the year 2017 and whose selling price > 10 lakhs.
### 3.How many swift cars are there with selling price < 4 Lakhs.
### 4.How many Automatic Transmission Petrol Car are of the year 2015 whose selling price is > 10 Lakhs.
### 5.List out Vehicles with Automatic Transmission and selling price < 1 Lakh.
### 6.How Many Petrol Vehicles are there with kms driven more than 50000kms and Year is between 2010 to 2015(both Yearincluded).
### 7.List out the cars whose price difference between present price and selling price is > 15 lakhs.
### 8.How many Petrol vehicles are there whose kms driven < 5000km and selling price < 50000.

In [ ]:
import pandas as pd
df=pd.read_csv("car data.csv")
df.head()

In [ ]:
df[((df["Car_Name"]=="ritz")&(df["Kms_Driven"]>=30000))]

In [ ]:
df[((df["Year"]==2017)&(df["Fuel_Type"]=="Petrol")&(df["Selling_Price"]>10))]

In [ ]:
df[((df["Car_Name"]=="swift")&(df["Selling_Price"]<4))]

In [ ]:
df[((df["Transmission"]=="Automatic")&(df["Fuel_Type"]=="Petrol")&(df["Year"]==2015)&(df["Selling_Price"]>10))]

In [ ]:
df[((df["Transmission"]=="Automatic")&(df["Selling_Price"]<1))]

In [ ]:
df[((df["Fuel_Type"]=="Petrol")&(df["Kms_Driven"]>50000)&((df["Year"]>=2010)&(df["Year"]<=2015)))]

In [ ]:
df[((df["Present_Price"]-df["Selling_Price"])>15)]

In [ ]:
df[((df["Fuel_Type"]=="Petrol")&(df["Kms_Driven"]<5000)&(df["Selling_Price"]<50000))].shape[0]

## Q63
### 1.Convert this file into a pandas Data Frame. (0.5 marks)
### 2.Display basic information like memory and data types for this data frame.(0.5 marks)
### 3.Display basic statistics like mean, std, quartiles, etc. for this data frame.(0.5 marks)
### 4.Create a correlation table for the data frame and comment about what kind of correlation is there between danceability and energy (0.5 marks)
### 5.Display first five rows for this data frame.(0.5 marks)
### 6.Display last five rows for this data frame. (0.5 marks)
### 7.Display the rows between 15 to 39 for this data frame. (0.5 marks)
### 8.Display the data only for last five rows and last five columns for this data frame. (0.5 marks)
### 9.Display the shape for this data frame. (0.5 marks)
### 10.Display the sum of NULL values for all the columns. (0.5 marks)
### 11.Remove first 3 columns from this Data Frame. (0.5 marks)
### 12.Remove first 10 rows from this Data Frame. (0.5 marks)
### 13.AŌer removing first 3 columns and first 10 rows from this data frame find outliers for the column popularity. (1 marks)
### 14.AŌer removing first 3 columns and first 10 rows from this data frame remove outliers for the column energy then display the data frame. (1 marks)
### 15.Display cross tabulation between time_signature and track_genre for actual Data Frame. (1 marks)

In [ ]:
import pandas as pd
df=pd.read_csv("spotify.csv")
df.info()
df.describe()

In [ ]:
df[["danceability", "energy"]].corr(numeric_only=True)

In [ ]:
df.head(5)

In [ ]:
df.tail(5)

In [ ]:
df.loc[15:39]

In [ ]:
df.iloc[-5:,-5:]

In [ ]:
df.shape

In [ ]:
df.isna().sum()

In [ ]:
df=df.drop(df.columns[:3],axis=1)
df

In [ ]:
df=df.iloc[10:]
df

In [ ]:
def find_outliers(ds,col):
    q1=ds[col].quantile(0.25)
    q3=ds[col].quantile(0.75)
    IQR=q3-q1
    low_val=q1-1.5*IQR
    high_val=q3+1.5*IQR
    print("Low ",low_val,"High ",high_val)
    ds=ds.loc[(ds[col]<low_val) | (ds[col]>high_val)]
    return ds

In [ ]:
find_outliers(df,"popularity")

In [ ]:
def remove_outliers(ds,col):
    q1=ds[col].quantile(0.25)
    q3=ds[col].quantile(0.75)
    IQR=q3-q1
    low_val=q1-1.5*IQR
    high_val=q3+1.5*IQR
    print("Low ",low_val,"High ",high_val)
    ds=ds.loc[(ds[col]>=low_val) & (ds[col]<=high_val)]
    return ds

In [ ]:
remove_outliers(df,"energy")

In [ ]:
pd.crosstab(df["time_signature"],df["track_genre"])

### Q68 Sort employees by Dept (Ascending) and Salary (Descending).
### After sorting, sort the index in descending order.
### Display the final DataFrame.

In [ ]:
import pandas as pd
data = {
 "EmpID":[101,102,103,104,105],
 "Dept":["IT","HR","IT","Finance","HR"],
 "Salary":[60000,45000,80000,75000,50000],
 "Age":[25,32,29,41,28]
}
df=pd.DataFrame(data)
df

In [ ]:
df.sort_values(by="Dept",ascending=True,inplace=True)
df

In [ ]:
df.sort_values(by="Salary",ascending=False,inplace=True)
df

In [ ]:
df.sort_index(inplace=True,ascending=False)
df

In [ ]:
df.sort_values(by=["Dept","Salary"],ascending=[True,False],inplace=True)
df

### Q69 Create a column Average using apply() row-wise.
### Create a column Grade based on:≥ 80 → Distinction≥ 60 → FirstOtherwise → Second
### Display final DataFrame

In [ ]:
import pandas as pd
df = pd.DataFrame({
 "Student":["A","B","C","D"],
 "Math":[70,45,90,60],
 "Science":[75,40,85,55]
})
df["Average"]=df[["Math","Science"]].apply(lambda x:x.mean(),axis=1)

In [ ]:
def grade(total):
    if total>=80:
        return "Distinction"
    elif total>=60:
        return "First"
    else:
        return "Second"
df['grade']=df["Average"].apply(grade)
df

### Q70 Replace "Absent" with 0.
### Convert the column to integer type.
### Print mean marks.
### Print number of students scoring above 50.

In [ ]:
df = pd.DataFrame({
 "Marks":["50","60","Absent","70","Absent"]
})
df.replace("Absent","0",inplace=True)
df

In [ ]:
df["Marks"]=df["Marks"].astype("int")

In [ ]:
df["Marks"].dtypes

In [ ]:
df.apply(lambda x:x.mean(),axis=0)

In [ ]:
df[df["Marks"]>=50].shape[0]

## Q71 Concatenate row-wise using outer join.Count total missing values.Sort the result by ID.

In [ ]:
df1 = pd.DataFrame({
 "ID":[1,2,3],
 "Name":["A","B","C"]
})
df2 = pd.DataFrame({
 "ID":[2,3,4],
 "Marks":[80,90,70]
})
df=pd.concat([df1,df2],axis=0,join="outer")
df

In [ ]:
df.isna().sum().sum(axis=0)

In [ ]:
df.sort_values("ID")

## PB 136

In [ ]:
import matplotlib.pyplot as plt
import networkx as nx
G=nx.DiGraph()
G.add_nodes_from(["A","B","C","D"])
G.add_edges_from([("A","B"),("B","C"),("C","D"),("D","A"),("B","D")])
nx.draw_networkx(G,node_size=850,node_color="lightblue",edge_color="black",width=2)
plt.show()

## PB137

In [ ]:
import matplotlib.pyplot as plt
import networkx as nx
G=nx.DiGraph()
G.add_nodes_from([0,1,2,3,4,5])
G.add_edges_from([(0,1),(1,1),(0,3),(1,3),(0,2),(2,0),(1,2),(2,1),(2,5),(1,5),(2,4)])
nx.draw_networkx(G,node_size=850,node_color="pink",edge_color="black",width=2)
plt.show()

## PB138 Create a boxplot of the distribution of temperatures in different cities. Take data from 'temperatures.csv'

In [ ]:
import pandas as pd
import seaborn as sns
df=pd.read_csv("temperatures.csv")
df.head()

In [ ]:
sns.boxplot(df[["New York","Los Angeles","Chicago"]])
plt.show()

## PB139
#### The following dictionary shows how five people follow each other on Instagram:
#### instagram = {'person1': [0,1,1,0,1], 'person2': [0,0,1,0,1], 'person3': [1,1,0,1,1],'person4':[1,1,1,0,0],'person5'[1,1,0,0,0]}
#### E.g., the list for person1 has the value on index 2 as 1 which means person1 followsperson3 and a directed edge should be
#### added from person1 to person3

In [ ]:
import networkx as nx
import matplotlib.pyplot as plt
G=nx.DiGraph()
instagram = {'person1': [0,1,1,0,1], 'person2': [0,0,1,0,1], 'person3': [1,1,0,1,1],'person4': [1,1,1,0,0], 'person5': [1,1,0,0,0]}
p=list(instagram.keys())
for i,person in enumerate(p):
    for j,val in enumerate(instagram[person]):
        if val==1:
            G.add_edge(person,p[j])
nx.draw_networkx(G,node_size=2500,node_color="red",edge_color="blue",width=2)
plt.show()

## PB72 Perform outer merge using indicator=True.Count:

In [ ]:
import pandas as pd
students = pd.DataFrame({
 "ID":[1,2,3,4],
 "Name":["A","B","C","D"]
})
marks = pd.DataFrame({
 "ID":[2,3,5],
 "Score":[85,90,75]
})
result=pd.merge(students,marks,how="outer",indicator=True)
result["_merge"].value_counts()

In [ ]:
students

In [ ]:
marks

## PB73 Group by Dept.Calculate mean, median, and max salary using agg().

In [ ]:
import pandas as pd
df = pd.DataFrame({
 "Dept":["IT","IT","HR","HR","Finance","Finance"],
 "Salary":[50000,70000,40000,60000,80000,75000]
})
df

In [ ]:
result=df.groupby("Dept").agg({"Salary":["mean","median","max"]})
print(result)

## PB74 Calculate range (max - min) per team using groupby + apply.

In [ ]:
import pandas as pd
df = pd.DataFrame({
 "Team":["A","A","A","B","B"],
 "Runs":[50,70,80,40,60]
})
result=df.groupby("Team").apply(lambda x:x.max()-x.min())
result

## PB75 Detect outliers using IQR method.Remove outliers.Print cleaned dataset

In [ ]:
import pandas as pd
df = pd.DataFrame({
 "Salary":[20000,22000,21000,25000,24000,300000]
})
df

In [ ]:
def remove_outliers(ds,col):
    q1=ds[col].quantile(0.25)
    q3=ds[col].quantile(0.75)
    IQR=q3-q1
    low_val=q1-1.5*IQR
    high_val=q3+1.5*IQR
    print("Low ",low_val,"High ",high_val)
    ds=ds.loc[(ds[col]>=low_val)&(ds[col]<=high_val)]
    return ds

In [ ]:
remove_outliers(df,"Salary")

## PB76 Find number of unique cities per department.Take one random employee per department.Display results.

In [ ]:
import pandas as pd
df = pd.DataFrame({
 "Dept":["IT","IT","HR","HR","Finance","Finance"],
 "Employee":["A","B","C","D","E","F"],
 "City":["X","X","Y","Z","X","Y"]
})
df.groupby("Dept")["City"].nunique()

In [ ]:
df.groupby("Dept")["Employee"].sample()

## PB77 Create a new column TotalAmount = Price × Quantity using apply() row-wise.Sort the DataFrame by TotalAmount in descending order.

In [ ]:
import pandas as pd
df = pd.DataFrame({
 "Product":["P1","P2","P3","P4","P5"],
 "Price":[100,200,150,300,250],
 "Quantity":[5,2,4,1,3]
})
df["TotalAmount"]=df.apply(lambda x:x["Price"]*x["Quantity"],axis=1)
sorted_value=df.sort_values(by="TotalAmount",ascending=False)
sorted_value

## PB78 Group employees by Department.Calculate total salary and average salary per department.Display departments where average salary is greater than 50,000

In [ ]:
import pandas as pd
df = pd.DataFrame({
 "Employee":["A","B","C","D","E"],
 "Dept":["IT","HR","IT","Finance","HR"],
 "Salary":[50000,40000,70000,80000,45000]
})
result=df.groupby("Dept").agg(TotalSalary=("Salary","sum"),AverageSalary=("Salary","mean"))
result1=result[result["AverageSalary"]>50000]
result1

## PB79 Find the number of employees per department using size().Find the employee with highest experience in each department using nth() or sorting.Display results.

In [ ]:
import pandas as pd
df = pd.DataFrame({
 "Dept":["IT","IT","HR","HR","Finance","Finance"],
 "Employee":["A","B","C","D","E","F"],
 "Experience":[2,5,3,7,4,6]
})
result=df.groupby("Dept")["Employee"].size()
result

In [ ]:
result1=df.sort_values(by="Experience",ascending=False)
res=result1.groupby("Dept").nth(0)
res

## PB66
Use the file movies.csv which contains 1629 rows and 18 columns. Read this csv file and display the basic information like
memory and data types for this data frame.
Write python code for the following cases:
### 1.List out Movies Released in Year 2019.
### 2.How Many Movies are having IMDB Rating > 7 (Display Number of Movies).
### 3.List out the Movies with ‘title’ and ‘story’ whose IMDB Votes > 20000.
### 4.List out Movies Released in Year 2018, Display only Movie Title with Release Date of Year 2018 Movies.
### 5.Display only Movie Title with its Wikipedia Link.

In [ ]:
import pandas as pd
df=pd.read_csv("movies.csv")
movies_release=df[df["year_of_release"]==2019]
movies_release

In [ ]:
imbd_rating=df[df["imdb_rating"]>7].shape[0]
imbd_rating

In [ ]:
movies=df[df["imdb_votes"]>20000][["original_title","story"]]
movies

In [ ]:
release_year=df[df["year_of_release"]==2018][["original_title"]]
release_year

In [ ]:
wiki_link=df[["original_title","wiki_link"]]
wiki_link

## PB65
1. Load the dataset into a pandas DataFrame (data_result.csv) and answer the following questions.
2. View the first few rows of the dataset
3. Check the shape of the dataset
4. View the first last rows of the dataset
5. Get summary statistics of numerical columns
6. Get summary statistics of numerical columns with 0.58 and 0.87 percentiles
7. Get summary statistics of all types of columns
8. Information of all columns
9. Check for missing values
10. Removing duplicates if duplicates
11. List out female students who have greater than 7 spi in all semesters.
12. Find number of students those who have greater than 8 spi in all 5 semesters.
13. Find outliers of sem 4 result. Also represent statistical analysis with visualization.(boxplot

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("data_result.csv")
df.head()

In [ ]:
df.shape

In [ ]:
df.tail()

In [ ]:
df.describe(include=[np.number])

In [ ]:
df.describe(include=[np.number],percentiles=[.58,.87])

In [ ]:
df.describe(include="all")

In [ ]:
df.info()

In [ ]:
df.isna().sum()

In [ ]:
remove_duplicates=df.drop_duplicates()
remove_duplicates

In [ ]:
df[(df["Gender"]=="Female")&(df["1st"]>7)&(df["2nd"]>7)&(df["3rd"]>7)&(df["4th"]>7)&(df["5th"]>7)]

In [ ]:
df[((df["Gender"]=="Female")|(df["Gender"]=="Male"))&(df["1st"]>8)&(df["2nd"]>8)&(df["3rd"]>8)&(df["4th"]>8)&(df["5th"]>8)]

In [ ]:
def find_outliers(ds,col):
    q1=ds[col].quantile(0.25)
    q3=ds[col].quantile(0.75)
    IQR=q3-q1
    low_val=q1-1.5*IQR
    high_val=q3+1.5*IQR
    print("Low",low_val,"High",high_val)
    ds=ds.loc[(ds[col]<low_val)|(ds[col]>high_val)]
    return ds

In [ ]:
import matplotlib.pyplot as plt
find_outliers(df,"4th")

In [ ]:
plt.boxplot(df["4th"])
plt.show()

In [ ]:
import seaborn as sns
sns.boxplot(df["4th"])

In [ ]:
df1 = pd.DataFrame({"A":[1,2]})
df2 = pd.DataFrame({"B":[3,4]})
result = pd.concat([df1, df2], axis=0)
result

In [ ]:
df = pd.DataFrame({
 "Dept":["IT","IT","HR"],
 "City":["A","A","B"]
})
result = df.groupby("Dept").nunique()
result

In [ ]:
print(result.loc["IT","City"])

## PB140 You have been given a dataset of car prices and their respective horsepower, mileage, and weight. You have beentasked to analyze the relationship between these variables and create a scatter plot to visualize the patterns. Dataset: The dataset, named "car_data.csv" :

In [ ]:
import pandas as pd
import plotly.express as px
import plotly.io as pio
import matplotlib.pyplot as plt
df=pd.read_csv("car_data.csv")
df[["Horsepower","Price","Mileage","Weight"]].corr()
px.scatter(df,x="Price",y=["Horsepower","Weight","Mileage"]).show()

## PB142 Use the file heights_weights.csv which contains 10000 non-null values for heights and weights. The Male column shows 1 if theperson is a Male and 0 if the person is a Female. Take file of dataset from:
 1. Convert this file into a pandas Data Frame.
 2. Display basic information like memory and data types for this data frame.
 3. Display basic statistics like mean, std, quartiles, etc. for this data frame.
 4. Create a correlation table for the data frame and comment about what kind ofcorrelation is there between Height and
Weight.
 5. Do Height and Weight contain any outliers? Answer by creating boxplots for both.
 6. Finally, create a scatter plot of Weight v/s H

In [ ]:
df=pd.read_csv("heights_weights.csv")
df.info()

In [ ]:
df.describe()

In [ ]:
df[["Height","Weight"]].corr()

In [ ]:
def find_outliers(ds,col):
    q1=ds[col].quantile(0.25)
    q3=ds[col].quantile(0.75)
    IQR=q3-q1
    low_val=q1-1.5*IQR
    high_val=q3+1.5*IQR
    print("Low",low_val,"High",high_val)
    ds.loc[(ds[col]<low_val)|(ds[col]>high_val)]
    return ds

In [ ]:
find_outliers(df,"Height")

In [ ]:
find_outliers(df,"Weight")

In [ ]:
import seaborn as sns
sns.boxplot(df["Height"])

In [ ]:
sns.boxplot(df["Weight"])

In [ ]:
px.scatter(df,x="Weight",y="Height").show()

## PB151 Plot heatmap,,annot=True,cmap="coolwarm", linewidths=1, linecolor="black"Show colorbar

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.DataFrame({
 "Math":[78,85,90,66,88],
 "Science":[80,82,89,70,85],
 "English":[75,88,92,60,84],
 "Computer":[90,91,95,72,89]
}, index=["S1","S2","S3","S4","S5"])
sns.heatmap(df,annot=True,cmap="coolwarm",linewidth=1,linecolor="black",cbar=True)
plt.show()

## PB152 Compute correlation, Plot heatmap with cmap="YlGnBu

In [ ]:
import pandas as pd
df = pd.DataFrame({
 "Height":[150,160,170,180,175],
 "Weight":[50,60,65,75,70],
 "Age":[20,22,25,30,28],
 "BMI":[22,24,23,26,25]
})
df[["Height","Weight","Age","BMI"]].corr()

In [ ]:
sns.heatmap(df,cmap="YlGnBu",linecolor="black",cbar=True,annot=True)
plt.show()

## PB153 Plot boxplot of Salary vs Dept with hue=Gender.

In [ ]:
df = pd.DataFrame({
 "Dept":["IT","IT","HR","HR","Finance","Finance"],
 "Salary":[50000,70000,40000,60000,80000,75000],
 "Gender":["M","F","M","F","M","F"]
})
plt.figsize=(20,20)
sns.boxplot(df,x="Salary",y="Dept",hue="Gender")
plt.show()

## PB 154 Plot boxplot and observe outlier

In [ ]:
import pandas as pd
df = pd.DataFrame({
 "Salary":[20000,22000,21000,23000,25000,300000]
})
sns.boxplot(data=df,x="Salary")
plt.show()

In [ ]:
def find_outliers(ds,col):
    q1=ds[col].quantile(0.25)
    q3=ds[col].quantile(0.75)
    IQR=q3-q1
    low_val=q1-1.5*IQR
    high_val=q3+1.5*IQR
    print("Low",low_val,"High",high_val)
    ds.loc[(ds[col]<low_val)|(ds[col]>high_val)]
    return ds

In [ ]:
find_outliers(df,"Salary")

## PB155 Create dataset of students with Marks and StudyHours.Use sns.scatterplot()Use hue for Grade.Use style for Gender.

In [ ]:
import pandas as pd
df = pd.DataFrame({
 "StudyHours":[2,3,5,6,8],
 "Marks":[50,60,75,85,95],
 "Gender":["M","F","M","F","M"]
})
def get_grade(marks):
    if marks >= 85:
        return "A"
    elif marks >= 70:
        return "B"
    elif marks >= 60:
        return "C"
    else:
        return "D"
df["Grade"]=df["Marks"].apply(get_grade)
sns.scatterplot(data=df,x="StudyHours",y="Marks",style="Gender",hue="Grade")

## PB156 Simple Bar Chart:Visualize total revenue of different departments.

In [ ]:
import pandas as pd
import plotly.express as px
import plotly.io as pio
df = pd.DataFrame({
 "Department": ["IT", "HR", "Finance", "Marketing"],
 "Revenue": [120000, 80000, 150000, 95000]
})
px.bar(df,x="Department",y="Revenue")

## PB157 Grouped Bar Chart: Compare yearly sales across regions.Compare yearly sales across regions.

In [ ]:
import pandas as pd
import plotly.express as px
import plotly.io as pio
df = pd.DataFrame({
 "Region": ["North","North","South","South"],
 "Year": ["2023","2024","2023","2024"],
 "Sales": [200,250,180,220]
})
px.bar(df,x="Region",y="Sales",text="Sales",color="Year",barmode="group",title="Yearly Sales Comparison Across Regions").show()

## PB158 Diverging Bar Chart: Display profit and loss of departments

In [ ]:
import pandas as pd
import plotly.express as px
import plotly.io as pio
df = pd.DataFrame({
 "Department": ["IT","HR","Finance","Marketing"],
 "Profit_Loss": [50000,-20000,70000,-15000]
})
px.bar(df,x="Department",y="Profit_Loss",color="Profit_Loss",text="Profit_Loss")

## PB159 2D Group Scatter: Analyze relationship between Height and Weight grouped by Gender

In [ ]:
import pandas as pd
import plotly.express as px
import plotly.io as pio
df = pd.DataFrame({
 "Height":[150,160,170,180,165],
 "Weight":[50,60,70,80,65],
 "Gender":["M","F","M","F","M"]
})
px.scatter(df,x="Height",y="Weight",color="Gender",color_discrete_map={"M":"blue","F":"pink"}).show()

## PB160 Bubble Scatter:Sales vs Profit where bubble size represents Quantity.

In [ ]:
df = pd.DataFrame({
 "Sales":[100,200,300,400],
 "Profit":[20,50,70,90],
 "Quantity":[10,30,50,80]
})
px.scatter(df,x="Sales",y="Profit",size="Quantity")

## PB161 3D Scatter:Visualize 3D coordinates with color grouping

In [ ]:
df = pd.DataFrame({
 "X":[1,2,3,4],
 "Y":[10,20,30,40],
 "Z":[5,15,25,35],
 "Category":["A","B","A","B"]
})
px.scatter_3d(df,x="X",y="Y",z="Z",color="Category")

## PB162 single Line Chart:Show yearly company growth.

In [ ]:
df = pd.DataFrame({
 "Year":[2020,2021,2022,2023,2024],
 "Revenue":[100,150,200,250,300]
})
px.line(df,x="Year",y="Revenue",markers=True).show()

## PB163 line Chart with Color Group: Track product sales trends

In [ ]:
df = pd.DataFrame({
 "Month":["Jan","Feb","Mar","Jan","Feb","Mar"],
 "Sales":[50,60,70,40,55,65],
 "Product":["A","A","A","B","B","B"]
})
px.line(df,x="Month",y="Sales",color="Product",markers=True)

## PB164 Line Chart with Color Group: Track product sales trends.

In [ ]:
df = pd.DataFrame({
 "Month":["Jan","Feb","Mar","Jan","Feb","Mar"],
 "Sales":[50,60,70,40,55,65],
 "Product":["A","A","A","B","B","B"]
})
px.line(df,x="Month",y="Sales",color="Product",markers=True)

## PB165 
#### Student Marks Distribution:
#### Create a dataset of 20 students containing their exam marks and grade category (A, B, C).
#### Perform the following:
#### Plot a histogram of Marks.
#### Set nbins = 5.
#### Use color = "Grade".
#### Display values using text_auto = True.
#### Add an appropriate title.

In [ ]:
df = pd.DataFrame({
 "Student": [f"S{i}" for i in range(1, 21)],
 "Marks": [45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
 48, 52, 58, 62, 68, 72, 78, 82, 88, 92],
 "Grade": ["C","C","C","B","B","B","A","A","A","A",
 "C","C","C","B","B","B","A","A","A","A"]
})
px.histogram(df,x="Student",y="Marks",nbins=5,color="Grade",text_auto=True,title="Student Marks Distribution")

## PB166 
- Create dataset of monthly sales transactions (30 values) and Region (North, South).Perform:
- Plot histogram of Sales.
- Use color="Region".
- Use pattern_shape="Region".
- Set nbins=6.
- Add title and custom color sequence.

In [ ]:
df = pd.DataFrame({
 "Sales":[100,120,150,180,200,220,250,270,300,320,
 110,130,160,190,210,230,260,280,310,330,
 105,125,155,185,205,225,255,275,305,325],
 "Region":["North"]*15 + ["South"]*15
})
px.histogram(df,x="Region",y="Sales",nbins=6,pattern_shape="Region",color="Region",color_discrete_sequence=["blue","red"])

## PB167 
Employee Age Distribution:Create dataset of employee ages and departments.
Perform:
Plot histogram of Age.
Use color="Department".
Use histfunc="count".
Set nbins=5.
Add proper title and width=700, height=400

In [ ]:
df = pd.DataFrame({
 "Age":[22,25,28,30,35,40,45,50,29,33,
 26,31,38,42,48],
 "Department":["IT","IT","HR","HR","Finance","Finance",
 "IT","HR","Finance","IT",
 "HR","Finance","IT","HR","Finance"]
})
px.histogram(df,x="Department",y="Age",color="Department",histfunc="count",nbins=5,width=700,height=400,title="Employee Age Distribution")

In [ ]:
df = pd.DataFrame({
 "Product":["A","B","C","D","E"],
 "Sales":[30,25,20,15,10]
})
fig=px.pie(df,values="Sales",names="Product",color_discrete_sequence=["blue","yellow","green","red","pink"],title="Product Market Share")
fig.update_traces(
    textinfo="percent+label",
    textposition="auto",
)
fig.show()

In [ ]:
df = pd.DataFrame({
 "Department":["IT","HR","Finance","Marketing"],
 "Budget":[50000,30000,40000,20000]
})
fig=px.pie(df,names="Department",values="Budget",title="Department Budget Allocation:",color_discrete_sequence=["blue","yellow","green","red"])
fig.update_traces(
    textinfo="percent+label",
    textposition="auto",
)
fig.show()